
name: 04A - Using Filters Activity

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main


jobs:
    echo:
     runs-on: ubuntu-latest
     steps:
       - run: echo "running is whenever a PR is opened or synchronized"

          