name: 05 workflow context

on: [workflow_dispatch, push]
 

env:
  NODE_VERSION: '20'
  APP_NAME: react-app

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: GitHub information
            run: |
                echo "Event: ${{ github.event_name }}"
                echo "Repository: ${{ github.repository }}"
                echo "Actor: ${{ github.actor }}"
                echo "SHA: ${{ github.event.workflow.name }}"
     
          - name: Show variables
            run: |
                echo "${{ env.APP_NAME }}"
                echo "${{ env.NODE_VERSION }}"
                            