name: 05 workflow context

run-name: 05 workflow context | DEBUG = ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        required: false
        default: 'false'

env:
  NODE_VERSION: '20'
  APP_NAME: react-app

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: GitHub information
            run: |
                echo "Event: ${{ github.event_name }}"
                echo "Repository: ${{ github.repository }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
     
          - name: Show environment variables
            run: |
                echo "${{ env.APP_NAME }}"
                echo "${{ env.NODE_VERSION }}"
                            
          - name: Variables from vars
            run: |
                echo "vars1: ${{ vars.MY_VAR}}"
                echo "vars2 ${{ vars.APP_NAME}}"