name: 06 expressions
run-name: 06 expressions | DEBUG ${{inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        type: boolean  
        default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
          - name: 'print debug input'
            if: ${{ inputs.debug }}
            run: |
              echo "triggered by ${{ github.event_name}} event"

          - name: 'print debug input'
            if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
            run: |
              echo "triggered by ${{ github.ref}} and ${{ github.ref_name}}"

          - name: 'message'
            run: |
              echo "Heelllooooo"
