name: 07 using variables

on:
  push:
  workflow_dispatch:
  

env:
    workflow_var: 'Hello workflow variable'

jobs:
    echo:
        runs-on: ubuntu-latest
        environment:
            name: prod
        env:
            job_var: 'blow job variable'
        steps:
        - name: 'print variables'
          env:
            step_var: 'Hello World'
            step_var2: 'hello world 2'
          run : |
                echo "step_var: ${{ env.step_var }}"
                echo "step_var2: ${{ env.step_var2 }}" 
                echo "job_var: ${{ env.job_var }}"
                echo "workflow_var: ${{ env.workflow_var }}"

    echo2:
        runs-on: ubuntu-latest
        steps:
        - name: 'print variables'
          run : |
                echo "ORG_OVERWRITTENV VAR : ${{ vars.OVERWRITTEN_VAR }}"
                echo "REPO VAR : ${{ vars.REPO_VAL }}"
    echo3:
        runs-on: ubuntu-latest
        steps:
        - name: 'print variables'
          run : |
                echo "ORG_OVERWRITTENV VAR : ${{ vars.OVERWRITTEN_VAR }}"
                echo "REPO VAR : ${{ vars.REPO_VAL }}"
                echo "ENV VAR : ${{ vars.TARGET_VAR }}"